### ISSUE TITLE
Search field default text not working correctly

### ISSUE THREAD

**Issue by marpa** [clas-web/unc-charlotte-variations#4]
The search field default text ("Search this site...") should disappear when users put their cursor in this field.  Ideally, this text should reappear when users move their cursor away and no other text is present.

Perhaps we should just use placeholder text, see:
http://www.w3schools.com/tags/att_input_placeholder.asp

Works for most modern browsers...

**Comment by cbarto11** [comment]
865193721b5419be4f60eb8bdac1af1190a242b7
